apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/your-github-username/job-application-copilot
    newName: ghcr.io/g3l00/job-application-copilot
    newTag: sha-4354bb29c91f
